### ISSUE TITLE
gff3_file_to_proteins_jtp.pl

### ISSUE THREAD

**Issue by mdeloger** [jtpoirier/proteomegenerator#2]
Hi,

in your actual snakefile you point to the script "gff3_file_to_proteins_jtp.pl" but the original script in transdecoder is called "gff3_file_to_proteins.pl".

So, is it a modified version of the script that we have to use or the original transdecoder one is ok ?

Thank you very much in advance for your answer

**Comment by jtpoirier** [comment]
Thanks for pointing this out. In earlier versions of TransDecoder, some of the gff3 conversion perl scripts produced different headers for bed files and fasta files. Brian Haas has kindly updated TransDecoder to improve header consistency. The default TransDecoder util scripts now work with ProteomeGenerator and I have updated master to use them.

I also updated some of the pgm rules to include automatic STAR and BLAST db creation, which you may find helpful.

Thanks for your help improving ProteomeGenerator and please do post anything else you run into that gives you trouble.
